### ISSUE TITLE
Website does not render correctly

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt-org.github.io#10]
Since the latest re-run of cobalt on the website, it isn't rendering correctly.

Looking closer, it appears the assets were either not pulled into "master" or that they somehow got messed up ("css", "png", and "svg" files in the root).

**Comment by tak1n** [comment]
I assume it's related to https://github.com/cobalt-org/cobalt.rs/issues/190 and https://github.com/cobalt-org/cobalt.rs/issues/183 which will be fixed in: https://github.com/cobalt-org/cobalt.rs/pull/191

Wanted to wait for feedback from other maintainers/contributors but as it seems pretty urgent for now I'm going to merge it. We can refactor it later.

**Comment by booyaa** [comment]
Still looking broken.

![screen shot 2017-05-24 at 17 48 08](https://cloud.githubusercontent.com/assets/192864/26415090/2e3b5f1e-40a9-11e7-8e28-7cc1a51df9ac.png)

**Comment by epage** [comment]
Yeah, the site is built from the version of Cobalt on crates.io but a new version hasn't been released since this was fixed.

I've tried reaching out to one of the project owners about the release process but haven't heard anything.

**Comment by epage** [comment]
New cobalt out and tried to upgrade the site but now running into:
```
$ [ $TRAVIS_BRANCH = source ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    cobalt import --branch master &&
    git config user.name "Cobalt Site Deployer" &&
    git config user.email "deploy@cobalt-org.github.io" &&
    git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
[info]   Using config file .cobalt.yml
[info]   Importing build to master
[info]   Import successful
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/cobalt-org/cobalt-org.github.io.git/'
```

**Comment by epage** [comment]
The website is now rendering correctly.  We're still not getting things pushed to it.  Will open a separate issue for that.
