### ISSUE TITLE
Document "install from source" requirements

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt-org.github.io#19]
Linux
- libssl-dev
- build-essential

Windows
- sass: [Windows 8.1 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk)
- syntect:

**Comment by epage** [comment]
Windows notes are being taken from @Geobert's research at https://github.com/cobalt-org/cobalt.rs/issues/180#issuecomment-354680930

**Comment by Geobert** [comment]
for syntect: https://www.microsoft.com/en-us/download/details.aspx?id=48159 & `call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" amd64`

**Comment by epage** [comment]
Looks like we're needing to drop windows-gnu for now (see https://github.com/cobalt-org/cobalt.rs/pull/352 ).   We need to include this in the instructions.

**Comment by epage** [comment]
@bluesir9 ran into some problems and we should incorporate it as well

https://github.com/cobalt-org/cobalt.rs/issues/380

**Comment by uwearzt** [comment]
I could give it a headstart for debian (the system i normally use).
