### ISSUE TITLE
[RFC]: Relooking?

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt-org.github.io#49]
When seeing the website, I can't help myself but think that it needs an overall refresh:

- the pages have different sizes
- the landing page is not really appealing, the footer is too high 
- Contribute, send directly to GitHub which is harsh. I think an introduction page to present the different repos (liquid and cobalt) and the gitter
- the Usage page is not very clear on `publish`: it sounds like after `publish` the post is visible but we still need a `build` to generate the post

and I didn't write everything down yet…

Thoughts?

**Comment by Geobert** [comment]
Of course, if green lighted, I'll do it. I'm no web designer but I think I can hack something if we stay on the same overall design :)

**Comment by epage** [comment]
Yeah, would love for someone to fix up the layout, see https://github.com/cobalt-org/cobalt-org.github.io/issues/20

> Of course, if green lighted, I'll do it. I'm no web designer but I think I can hack something if we stay on the same overall design :)

I'll try to upload some changes I have tonight after that, feel free.

> Contribute, send directly to GitHub which is harsh. I think an introduction page to present the different repos (liquid and cobalt) and the gitter

Maybe its just me but "harsh" feels strong.  We have a single-sourced page for contributing in a medium targeted to contributors.  The main thing lacking is pointing people to liquid but we also don't point people to pulldown or other dependencies, so not sure where the line is on that.

Do you have any clarifying or additional thoughts to help me understand the problem here?

> the Usage page is not very clear on publish: it sounds like after publish the post is visible but we still need a build to generate the post

Framed differently, you feel it makes it sound publish makes the site rebuild rather than modifying the source of the site?  Does this problem also exist with `cobalt new`?  If not, what is different between them?

**Comment by Geobert** [comment]
> Maybe its just me but "harsh" feels strong. We have a single-sourced page for contributing in a medium targeted to contributors. The main thing lacking is pointing people to liquid but we also don't point people to pulldown or other dependencies, so not sure where the line is on that.

Yeah, "harsh" is too strong, still this thing with English not being my mother tongue ^^' Let say I was surprise to go out of the website by clicking on a button in the navigation button.
As for liquid, it's because this one is under cobalt.org as well :)

> Framed differently, you feel it makes it sound publish makes the site rebuild rather than modifying the source of the site? Does this problem also exist with cobalt new? If not, what is different between them?

Maybe it's me here, when creating a new post, I'm expecting it to be in draft state whereas publishing something has a "put online for everyone to see" vibe in it.

**Comment by epage** [comment]
> Let say I was surprise to go out of the website by clicking on a button in the navigation button.

Yeah, I have a subtle UX of a non-standard color.  Granted, that is also to de-emphasize (ideally users do not have to be contributors) in contrast to "help" which I emphasize.

If we keep it as-is, one option is a "browse out of" icon.  I think those exist and are common?  Might get too cluttered though.

> Maybe it's me here, when creating a new post, I'm expecting it to be in draft state whereas publishing something has a "put online for everyone to see" vibe in it.

Ok, so it is less the text and more of counteracting assumptions based on the command name?

**Comment by Geobert** [comment]
> If we keep it as-is, one option is a "browse out of" icon. I think those exist and are common? Might get too cluttered though.

I can try that :)

> Ok, so it is less the text and more of counteracting assumptions based on the command name?

Exactly the name made me think the post will go visible, that's why I think documenting all the steps can help :)
