### ISSUE TITLE
LICENSE and reusing you CI

### ISSUE THREAD

**Issue by thinkofher** [cobalt-org/cobalt-org.github.io#82]
Hey,

I'm thinking about switching from jekyll to cobalt and I find your github workflows for cobalt.rs homepage very interesting. Could I reuse them for my personal website? What is the license for this code?

btw: cobalt.rs is awesome 👍, great replacement for jekyll imho

**Comment by epage** [comment]
Glad you like it! I know it has a long way more to go (at least compared to where I want it to be).  I'm looking at dedicating my fridays to my personal projects.  Once I wrap up some features for [git-stack](https://github.com/epage/git-stack), I'm going to put some more attention to cobalt.

As for the licensing, I presume it to be non-copyrightable and not needing of a license, but a lawyer would better be able to speak on it.

**Comment by epage** [comment]
Go for it
