### ISSUE TITLE
`cobalt serve` does not default to port 3000

### ISSUE THREAD

**Issue by skierpage** [cobalt-org/cobalt-org.github.io#94]
http://cobalt-org.github.io/docs/usage/ says **serve**:
____
Serve your site at `127.0.0.1:3000`
```
$ cobalt serve
# Include drafts
$ cobalt serve --drafts
```
This provides live reload; it will re-generate your site as you add or change content.

Use the `--host` argument to listen on a different address (ex. 0.0.0.0/INADDR\_ANY); the default is `localhost`.  Use `--port` (or `-P`) to listen on a different TCP port number (default: 3000).
____
but `cobalt serve` actually uses the first available port in the range 1024..9000 (see [`get_available_port()`](https://github.com/cobalt-org/cobalt.rs/blob/master/crates/file-serve/src/lib.rs#L221)). It prints the hostname and port it listens on to stderr, e.g.
```
Server Listening on http://localhost:1025
```

 `cobalt serve --help` doesn't say it defaults to 3000, though [it looks like](https://github.com/cobalt-org/cobalt.rs/blob/master/crates/file-serve/src/lib.rs#L67) that if `get_available_port()` fails, cobalt will use port 3000 (and probably fail)

**Comment by skierpage** [comment]
Thanks. FYI you fixed [Start/Getting started](http://cobalt-org.github.io/getting-started/) but not the similar text in [Reference > Usage](http://cobalt-org.github.io/docs/usage/) that I saw.

**Comment by epage** [comment]
Thanks, I fixed it
